var settings = {
	author: "Generated by 'Website to Chrome App'",
	appendix: ' chrome app'
};

var app = {

	updateButton: function() {
		if (app.$form.isValid() !== !app.$generateButton.hasClass('is-disabled'))
			app.$generateButton[!app.$form.isValid() ? 'add' : 'remove' + 'Class']('is-disabled');
	},

	generate: function(e) {
		e.preventDefault();

		// Gather context for templates

		var formData = {};
		$.each($('form input, form textarea'), function(i, o) {
			formData[o.id] = $(o).is('[type="checkbox"]') ?
				o.checked : o.value;
		});

		var context = {};
		$.each([
			'name',
			'desc',
			'url',
			'windowHeight',
			'windowWidth',
			'saveState'
		], function(i, o) {
			context[o] = formData[o];
		});


		$.extend(context, {
			author: settings.author,
			partition: !formData.saveState ? '' : generateTemplate(
				'persist:{{nameId}}-chromeapp'
			)({
				nameId: friendlyfy(formData.name).toLowerCase()
			})
		});


		// Generate files

		var zip = new JSZip();
		var mainFolder = zip.folder(friendlyfy(context.name));

		var templates = [
			'manifest.json',
			'window.html',
			'background.js',
		];

		$.each(templates, function(i, fileName) {
			mainFolder.file(fileName, generateTemplate(
				normalizeIndentation(
					$('[data-fileName="' + fileName + '"]').html()
					.replace('\n', '') //remove first line break
				)
			)(context));
		});

		// Add icon
		app.getIcon(function(dataUri) {
			mainFolder.file(
				"128.png",
				dataUri.replace("data:image/png;base64,", ""), { base64: true }
				//jsZip's API needs the beginning removed
			);

			// Download
			saveAs(
				zip.generate({ type: "blob" }),
				friendlyfy(context.name) + ".zip"
			);
		});
	},

	changedName: function() {
		var earlyVal = $("#name").val();

		setTimeout(function() {
			var name = $("#name").val();

			// set preview app title

			$(".app")[(name ? "add" : "remove") + "Class"]('name-active');
			$(".app-desc").text(name);

			// update boilerplate desc text
			if (name && !$('#desc').val() ||
				$('#desc').val() === earlyVal + settings.appendix)
				$('#desc').val(name + settings.appendix);
		});
	},

	iconChange: function() {

		app.getIcon(function(dataUri) {
			var iconExists = !!dataUri;
			dataUri = dataUri || miniGif;

			// update app-icon preview
			$('.app-icon').attr('src', dataUri);
			$('.app')[(iconExists ? "add" : "remove") + "Class"]('icon-active');

			// update icon preview
			$('#icon + img').attr('src', dataUri);

			// img has to be loaded
			var loadedIconIsValid = !iconExists ||
				$('#icon + img').height() === 128 &&
				$('#icon + img').width() === 128;

			$('label[for="icon"] + aside')[(loadedIconIsValid ? "remove" : "add") + "Class"]('has-error');
		});
	},

	getIcon: function(callback) {
		var file = $('#icon')[0].files[0];
		if (!file) {
			callback();
			return;
		}

		reader = new FileReader();
		reader.addEventListener("load", function() {
			callback(reader.result);
		}, false);

		reader.readAsDataURL(file);
	},

	urlChange: function() {
		var $url = $('#url');
		var url = $url.val();

		if (url)
			$("#window iframe").attr("src", url);

		// try and update icon from favicon
		/*
		if (!url) {
			$url.parent().removeAttr('data-error-text');
			return;
		}

		$.ajax({
				url: url,
			})
			.done(function(res) {
				$url.parent().removeAttr('data-error-text');

				console.log("success");
				$(res).filter('[rel*="icon"]').each(function(index, el) {
					$('#icon ~ img').remove();
					$("<img/>").attr("src", el.attr("href"))
						.insertAfter($('#icon'))
				});
			})
			.fail(function() {
				$url.parent().attr('data-error-text', "Doesn't resolve");
				console.log("error");
			})
			.always(function() {
				console.log("complete");
			});
			*/

	},

	init: function() {
		app.$generateButton = $('button[type="submit"]');
		app.$form = $('form');

		app.$form.on('keyup change', app.updateButton);
		app.updateButton();

		app.$form.on('submit', app.generate);

		$('#windowHeight').on('keydown change', function() {
			setTimeout(function() {
				$("#window").height(Math.max(100, $("#windowHeight").val()));
			});
		});
		$('#windowWidth').on('keydown change', function() {
			setTimeout(function() {
				$("#window").width(
					Math.max(100, $("#windowWidth").val())
				);
			});
		});

		$('#name').on('keydown change', app.changedName);
		if ($('#name').val())
			app.changedName();

		$('#url').on('keydown change', debounce(app.urlChange, 500));
		app.urlChange();

		$('#icon').on('change', app.iconChange);
		app.iconChange();


		// various ui tweaks

		// select text in links you can't click
		$('a[href*="chrome://"]').on('mouseenter', function() {
			console.log("awd");
			selectElement($(this).get(0));
		});
	}
};

$(app.init);


/* Helpers */

// Normalize string indentation relative to indentation of first line
var normalizeIndentation = function(string, spaces) {
	spaces = spaces || 4;

	// var startsWithIndentation = /^(\u0020{4}|\t)/gm;

	// var dedent = function(string) {
	// 	console.log(string, string.match(startsWithIndentation));
	// 	if (string.match(startsWithIndentation))
	// 		string = string.replace(startsWithIndentation, '');
	// 	else
	// 		return string;

	// 	dedent(string)
	var firstLineIndents =
		string.split('\n')[0]
		.match(/(\u0020{4}|\t)/g),
		levels = firstLineIndents && firstLineIndents.length;

	return string.replace(
		new RegExp('^(\u0020{' + spaces + '}|\t){0,' + levels + '}', 'gm'),
		''
	);
};

// escapes strings with '-' and makes them file/folder name friendly
var friendlyfy = function(string) {
	return string.replace(/\W/g, '-');
};

// check form validity
$.fn.isValid = function() {
	return this[0].checkValidity();
};

// minimal templating engine
var generateTemplate = function(string) {
	string = string.replace(/\n/g, '\\n');
	string = string.replace(/\'/g, '\"');
	string = string.replace(/\"/g, '\"');
	return new Function(
		'context',
		"return '" + string.replace(/{{\s*([^}]+)\s*}}/g, "'+context.$1+'") + "';"
	);
};

function debounce(fn, delay) {
	var timer = null;
	return function() {
		var context = this,
			args = arguments;
		clearTimeout(timer);
		timer = setTimeout(function() {
			fn.apply(context, args);
		}, delay);
	};
}

function throttle(fn, threshhold, scope) {
	threshhold || (threshhold = 250)
	var last,
		deferTimer;
	return function() {
		var context = scope || this;

		var now = +new Date(),
			args = arguments;
		if (last && now < last + threshhold) {
			// hold on to it
			clearTimeout(deferTimer);
			deferTimer = setTimeout(function() {
				last = now;
				fn.apply(context, args);
			}, threshhold);
		} else {
			last = now;
			fn.apply(context, args);
		}
	};
}

var miniGif = "data:image/gif;base64,R0lGODlhAQABAID/AMDAwAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="; // small transparent gid

function selectElement(element) {
	var range,
		selection;

	if (document.body.createTextRange) {
		range = document.body.createTextRange();
		range.moveToElementText(element);
		range.select();
	} else if (window.getSelection) {
		selection = window.getSelection();
		range = document.createRange();
		range.selectNodeContents(element);
		selection.removeAllRanges();
		selection.addRange(range);
	}
}
